server.port=8081
cors.originPatterns=http://localhost:3000,http://localhost:8081
file.upload-dir=/home/kaio/Downloads/curso de spring/UploadDir
#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/clinica_oftamologica?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin123
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
springdoc.pathsToMatch=/auth/**,/api/**/v1/**
springdoc.swagger-ui.use-root-path=true

# Configurações do Keycloak
keycloak.auth-server-url=http://localhost:8080/auth
keycloak.realm=clinica-oftamologica
keycloak.credentials.secret=e4d286dc-64ae-4623-93f9-1973d7466048
keycloak.principal-attribute=preferred_username
# Remover keycloak.bearer-only
# keycloak.bearer-only=true

# Configuração OAuth2
spring.security.oauth2.client.registration.keycloak.client-id=clinica-oftamologica-app
spring.security.oauth2.client.registration.keycloak.client-secret=e4d286dc-64ae-4623-93f9-1973d7466048
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid, profile, email
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak

# Informações sobre o provider Keycloak
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8080/auth/realms/clinica-oftamologica/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8080/auth/realms/clinica-oftamologica/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8080/auth/realms/clinica-oftamologica/protocol/openid-connect/certs
